### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by czystyl** [graphql-community/graphql-directive-computed-property#2]

**Comment by sibelius** [comment]
you should polyfill babel-polyfill to make this work

**Comment by czystyl** [comment]
Yes, but I'd like to add this to the library and not force the user to install it. What do you think about it?

**Comment by sibelius** [comment]
bad idea, let user polyfill

in some environment polyfill is not needed, so it should not be included

**Comment by czystyl** [comment]
Good point, and good idea so we can close it :) 

Thanks for your input 👍

**Comment by taylorgoolsby** [comment]
Shouldn't [transform-runtime](https://www.npmjs.com/package/babel-plugin-transform-runtime) be used instead?

regenerator-runtime is no longer a viable option since it does not create a global variable anymore. The suggested method seems to be for third party packages to use transform-runtime. Citation: https://github.com/facebook/regenerator/issues/363#issuecomment-440380606

babel-polyfill does work, but now that regenerator-runtime is no longer an option, the only option for people who do not want to use babel-polyfill is to use transform-runtime, but transform-runtime must be included in the third party package.
